"""Markdown template semantics and meaningful generated validation invariants."""

from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from darrow_git import templates
from darrow_git.evidence_identity import escape_tsv
from darrow_git.messages import validate_attribution, validate_subject
from darrow_git.process import RefusalError


@settings(max_examples=50, derandomize=True)
@given(
    st.text(
        alphabet="abcdefghijklmnopqrstuvwxyz0123456789 ", min_size=1, max_size=60
    ).filter(lambda value: bool(value.strip()))
)
def test_generated_subjects_keep_length_and_attribution_guards(text: str) -> None:
    subject = "fix: " + text.strip()
    validate_subject(subject, "subject")
    with pytest.raises(RefusalError):
        validate_subject(subject + ".", "subject")
    with pytest.raises(RefusalError):
        validate_attribution(subject + "\nGenerated by Claude", "commit messages")


@settings(max_examples=50, derandomize=True)
@given(st.text(alphabet="abc\\\t\n\r😀", max_size=100))
def test_tsv_never_contains_raw_record_delimiters(text: str) -> None:
    escaped = escape_tsv(text)
    assert not any(char in escaped for char in "\t\n\r")
    # Decode the exact four escape forms used by gh @tsv, without interpreting
    # arbitrary Python/JSON escapes or corrupting Unicode.
    restored = []
    index = 0
    mapping = {"t": "\t", "r": "\r", "n": "\n", "\\": "\\"}
    while index < len(escaped):
        if escaped[index] == "\\":
            restored.append(mapping[escaped[index + 1]])
            index += 2
        else:
            restored.append(escaped[index])
            index += 1
    assert "".join(restored) == text


@pytest.mark.parametrize(
    "body,message",
    [
        ("## Different\ncontent", "missing"),
        ("## Why\n\n## What\ntext", "empty"),
        ("## Why\ncontent\n## What\n<!-- remove -->", "comments"),
    ],
)
def test_template_invalid(repository: Path, body: str, message: str) -> None:
    path = repository / "PULL_REQUEST_TEMPLATE.md"
    path.write_text("## Why\n## What\n")
    with pytest.raises(RefusalError, match=message):
        templates.validate(path, body)


def test_template_fences_and_selection(
    repository: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    directory = repository / ".github" / "PULL_REQUEST_TEMPLATE"
    directory.mkdir(parents=True)
    first = directory / "one.md"
    first.write_text(
        "\ufeff## Why\n```\n## Not a heading\n```\n## What\n", encoding="utf-8"
    )
    assert templates.select("") == first
    templates.validate(
        first, "## Why\n### Child\ncontent\n## What\n```\n<!-- literal -->\n```\n"
    )
    (directory / "two.md").write_text("# Second")
    with pytest.raises(RefusalError, match="multiple PR templates"):
        templates.select("")
    assert templates.select("one.md") == first
    with pytest.raises(RefusalError, match="not available"):
        templates.select("missing.md")
    assert templates.select("", inspecting=True) is None
    assert "multiple PR templates" in capsys.readouterr().out
    templates.show(first)
    assert "pr template" in capsys.readouterr().out
    root = repository / "PULL_REQUEST_TEMPLATE.md"
    root.write_text("## Root\n" + "text\n" * 101)
    assert templates.select("") == root
    with pytest.raises(RefusalError, match="single template"):
        templates.select("one.md")
    templates.show(root)
    assert "truncated at 100 lines" in capsys.readouterr().out
