"""Public validation refuses malformed requests before mutation."""

from pathlib import Path

import pytest

from darrow_git import branch, commit, evidence_options, pr, publication
from darrow_git.process import RefusalError, git


@pytest.mark.parametrize(
    "task,args,code",
    [
        (False, [], 64),
        (True, ["other"], 64),
        (False, ["create"], 2),
        (True, ["prepare", "fix/181-work"], 2),
        (False, ["create", "--from"], 2),
        (False, ["create", "--ticket-token"], 2),
        (False, ["create", "--ticket-token", ""], 2),
        (False, ["create", "--at"], 2),
        (True, ["prepare", "--at", ""], 2),
        (False, ["create", "--unknown"], 2),
        (False, ["create", "feat/a", "feat/b"], 2),
        (False, ["create", "feat/a", "--at", "path"], 2),
        (False, ["create", "feat/a", "--worktree", "--at", ""], 2),
        (False, ["create", "feat/a", "--from", "missing"], 2),
        (False, ["create", "feature/wrong"], 5),
        (False, ["create", "feat/Upper"], 5),
        (False, ["create", "feat/" + "a" * 56], 5),
        (False, ["create", "feat/181-work", "--ticket-token", "/181"], 5),
        (False, ["create", "feat/work-181", "--ticket-token", "181"], 5),
        (False, ["create", "feat/181-181", "--ticket-token", "181"], 5),
        (False, ["create", "feat/181-UPPER", "--ticket-token", "181"], 5),
        (True, ["discover"], 2),
        (True, ["discover", "--ticket-token", ""], 2),
        (True, ["discover", "--ticket-token", "token..bad"], 5),
        (True, ["discover", "--ticket-token", "x" * 56], 5),
    ],
)
def test_branch_invalid(
    repository: Path, task: bool, args: list[str], code: int
) -> None:
    before = git("show-ref")
    with pytest.raises(RefusalError) as failure:
        branch.run(args, task=task)
    assert failure.value.code == code
    assert git("show-ref") == before


@pytest.mark.parametrize(
    "args,code",
    [
        ([], 64),
        (["diff"], 64),
        (["diff", "missing"], 64),
        (["commit"], 2),
        (["commit", "-m"], 2),
        (["commit", "-m", "invalid"], 5),
        (["commit", "-m", "feat: period."], 5),
        (["commit", "-m", "feat: " + "x" * 70], 5),
        (["commit", "-m", "feat: example", "-m", "Generated by Claude"], 6),
        (["commit", "-m", "feat: example", "."], 7),
        (["commit", "-m", "feat: example", "*.py"], 7),
        (["commit", "-m", "feat: example"], 3),
        (["retry"], 2),
        (["retry", "--wrong"], 2),
        (["retry", "-m"], 2),
        (["remediate", "--command"], 2),
        (["remediate", "--unknown"], 2),
        (
            [
                "remediate",
                "--after-hook-failure",
                "--refresh-staged",
                "tracked.txt",
                "-m",
                "fix: example",
            ],
            2,
        ),
        (
            [
                "retry",
                "--after-hook-failure",
                "--refresh-staged",
                "tracked.txt",
                "-m",
                "fix: example",
            ],
            7,
        ),
    ],
)
def test_commit_invalid(repository: Path, args: list[str], code: int) -> None:
    before = git("write-tree"), git("rev-parse", "HEAD")
    with pytest.raises(RefusalError) as failure:
        commit.run(args)
    assert failure.value.code == code
    assert (git("write-tree"), git("rev-parse", "HEAD")) == before


@pytest.mark.parametrize(
    "args,code",
    [
        ([], 64),
        (["create"], 2),
        (["create", "--title", "feat: x"], 2),
        (["create", "--title"], 2),
        (["create", "-b"], 2),
        (["create", "--base", ""], 2),
        (["inspect", "--base"], 2),
        (["create", "--template"], 2),
        (["create", "--unknown"], 2),
        (["create", "-b", " \n"], 2),
        (["inspect", "--template", "../file"], 2),
        (["inspect", "--template", ".hidden"], 2),
    ],
)
def test_pr_invalid(repository: Path, args: list[str], code: int) -> None:
    with pytest.raises(RefusalError) as failure:
        pr.run(args)
    assert failure.value.code == code


@pytest.mark.parametrize("args", [["--expected-head"], ["--base", ""], ["--force"]])
def test_publication_parse_refusal(args: list[str]) -> None:
    with pytest.raises(RefusalError, match="push: none") as failure:
        publication.parse(args)
    assert failure.value.code == 4


@pytest.mark.parametrize(
    "args",
    [
        [],
        ["--expected-head", "HEAD"],
        ["--body-file"],
        ["--unknown"],
        ["--expected-head", "a" * 40],
        ["--image", "a.png"],
        ["--image", "a.png", "--explanation", "text"],
        ["--video", "a.mp4", "--alt", "text"],
        ["--image", "a.png", "--alt", "   "],
        ["--image", "a.png", "--alt", "bad\nline"],
        [
            "--expected-head",
            "a" * 40,
            "--body-file",
            "body",
            *(["--image", "x.png", "--alt", "Image"] * 51),
        ],
    ],
)
def test_evidence_parse_refusal(args: list[str]) -> None:
    with pytest.raises(RefusalError):
        evidence_options.parse(args)
