#!/usr/bin/env bash
# Deterministic git steps for the create-commit skill.
# stdout is read by a model: print only decision-relevant data, never raw
# intermediate git output. Checkable invariants (conventional format, no AI
# attribution, staged-set integrity) are enforced here, not in the prompt.
set -euo pipefail

# `head` would SIGPIPE git under pipefail on large diffs; awk consumes input.
truncate_lines() { awk 'NR<=300'; }

in_conflict() { [[ -n "$(git ls-files -u)" ]]; }

cmd=${1:-}
shift || true

case "$cmd" in
  inspect)
    # Mode-aware: with a staged set the commit scope is already decided, so
    # only message context is printed. Without one, selection context.
    if in_conflict; then
      echo "## mode: conflict (merge/rebase in progress — do not commit; inform the user)"
      echo "## unmerged files"
      git diff --name-only --diff-filter=U
    elif ! git diff --cached --quiet; then
      echo "## mode: staged (commit exactly this set; pass no paths)"
      echo "## staged files"
      git diff --cached --name-status
      echo "## not included (unstaged/untracked)"
      git diff --name-only
      git ls-files --others --exclude-standard
      echo "## recent subjects"
      git log -5 --format='%s' 2>/dev/null || true
      echo "## staged diff (truncated at 300 lines)"
      git diff --cached --unified=2 | truncate_lines
    else
      echo "## mode: unstaged (select only files belonging to the change)"
      echo "## unstaged files"
      git diff --name-status
      echo "## untracked files"
      git ls-files --others --exclude-standard
      echo "## recent subjects"
      git log -5 --format='%s' 2>/dev/null || true
      echo "## unstaged diff (truncated at 300 lines)"
      git diff --unified=2 | truncate_lines
    fi
    ;;

  diff)
    # Compact diff of specific working-tree paths, for choosing what to stage.
    if [[ $# -eq 0 ]]; then
      echo "error: diff needs at least one path" >&2
      exit 64
    fi
    for p in "$@"; do
      if git ls-files --error-unmatch -- "$p" >/dev/null 2>&1; then
        git diff --unified=2 -- "$p" | truncate_lines
      elif [[ -f "$p" ]]; then
        # Untracked: show as an all-new diff.
        git diff --no-index --unified=2 -- /dev/null "$p" | truncate_lines || true
      else
        echo "error: no such file: $p" >&2
        exit 64
      fi
    done
    ;;

  commit)
    # commit [-m <msg>]... [<path>]...
    # Paths (if given) are staged explicitly; -m repeats like git commit.
    files=()
    msgs=()
    while [[ $# -gt 0 ]]; do
      case "$1" in
        -m)
          if [[ $# -lt 2 ]]; then
            echo "error: -m needs a value" >&2
            exit 2
          fi
          msgs+=("$2")
          shift 2
          ;;
        *)
          files+=("$1")
          shift
          ;;
      esac
    done
    if [[ ${#msgs[@]} -eq 0 ]]; then
      echo "error: no -m message given" >&2
      exit 2
    fi

    if in_conflict; then
      echo "error: merge/rebase in progress — resolve conflicts first; do not commit" >&2
      exit 8
    fi

    # Staged-set integrity: an existing staged set IS the commit set.
    if ! git diff --cached --quiet && [[ ${#files[@]} -gt 0 ]]; then
      echo "error: a staged set exists; pass no paths (commit exactly the staged set)" >&2
      exit 7
    fi
    # No sweep shortcuts: only explicit literal paths.
    for f in ${files[@]+"${files[@]}"}; do
      if [[ "$f" == "." || "$f" == ".." || "$f" == -* || "$f" == :* || "$f" == *[\*\?\[]* ]]; then
        echo "error: only explicit file paths allowed, got: $f" >&2
        exit 7
      fi
    done

    subject=${msgs[0]%%$'\n'*}
    if ! [[ "$subject" =~ ^(feat|fix|refactor|perf|docs|test|chore|build|ci|style|revert)(\([^\)]+\))?\!?:\ [^[:space:]] ]]; then
      echo "error: subject not Conventional Commits format: $subject" >&2
      exit 5
    fi
    if [[ ${#subject} -gt 72 ]]; then
      echo "error: subject exceeds 72 chars (${#subject})" >&2
      exit 5
    fi
    if [[ "$subject" == *. ]]; then
      echo "error: subject has trailing period" >&2
      exit 5
    fi
    full_message=$(printf '%s\n\n' "${msgs[@]}")
    # Attribution needs tool context: "generated by openapi-generator" is
    # legitimate prose, "Generated using Claude Code" is not.
    # Herestring, not a pipe: grep -q exits at the first match, and on a
    # >64KB message the writer's SIGPIPE (141) would make pipefail discard
    # the match — silently disabling this check.
    if grep -qiE 'co-authored-by:.*\b(claude|gpt|chatgpt|codex|copilot|cursor|gemini|ai)\b|co[- ]?authored[- ]by +(claude|gpt|chatgpt|codex|copilot|cursor|gemini)\b|(generated|built|written|created|made|assisted)[- ](with|by|using) +\[?(claude|gpt|chatgpt|codex|copilot|cursor|gemini|an? ai\b|ai\b)|🤖' <<< "$full_message"; then
      echo "error: AI attribution is not allowed in commit messages" >&2
      exit 6
    fi

    if [[ ${#files[@]} -gt 0 ]]; then
      git add -- "${files[@]}"
    fi
    if git diff --cached --quiet; then
      echo "error: nothing staged" >&2
      exit 3
    fi

    msg_args=()
    for m in "${msgs[@]}"; do msg_args+=(-m "$m"); done
    out=$(git commit -q "${msg_args[@]}" 2>&1) || {
      # Commit failed (hook, identity, etc.): surface verbatim, never bypass.
      echo "$out" >&2
      exit 4
    }
    git log -1 --format='%h %s'
    ;;

  retry)
    # A hook-failure retry may refresh only named paths already in the index.
    # It then delegates to `commit`, retaining that command's normal checks and
    # hook execution rather than creating a bypass path.
    refresh_files=()
    msgs=()
    after_hook_failure=0
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --after-hook-failure)
          after_hook_failure=1
          shift
          ;;
        --refresh-staged)
          shift
          while [[ $# -gt 0 && "$1" != -m && "$1" != --after-hook-failure && "$1" != --refresh-staged ]]; do
            refresh_files+=("$1")
            shift
          done
          ;;
        -m)
          if [[ $# -lt 2 ]]; then
            echo "error: -m needs a value" >&2
            exit 2
          fi
          msgs+=("$2")
          shift 2
          ;;
        *)
          echo "error: retry accepts only --after-hook-failure, --refresh-staged, and -m" >&2
          exit 2
          ;;
      esac
    done
    if [[ $after_hook_failure -ne 1 || ${#refresh_files[@]} -eq 0 || ${#msgs[@]} -eq 0 ]]; then
      echo "error: retry needs --after-hook-failure, --refresh-staged <path>..., and -m" >&2
      exit 2
    fi
    if in_conflict; then
      echo "error: merge/rebase in progress — resolve conflicts first; do not commit" >&2
      exit 8
    fi
    if git diff --cached --quiet; then
      echo "error: retry needs an existing staged set" >&2
      exit 7
    fi
    for f in ${refresh_files[@]+"${refresh_files[@]}"}; do
      if [[ "$f" == "." || "$f" == ".." || "$f" == -* || "$f" == :* || "$f" == *[\*\?\[]* ]]; then
        echo "error: only explicit file paths allowed, got: $f" >&2
        exit 7
      fi
      staged_path=$(git diff --cached --name-only -- "$f")
      if [[ "$staged_path" != "$f" ]]; then
        echo "error: retry path is not in the existing staged set: $f" >&2
        exit 7
      fi
    done
    git add -- "${refresh_files[@]}"
    msg_args=()
    for m in "${msgs[@]}"; do msg_args+=(-m "$m"); done
    exec "$0" commit "${msg_args[@]}"
    ;;

  *)
    echo "usage: commit.sh inspect | diff <path>... | commit [-m <msg>]... [<path>]... | retry --after-hook-failure --refresh-staged <path>... -m <msg>" >&2
    exit 64
    ;;
esac
