import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from darrow_tickets_github.arguments import parse
from darrow_tickets_github.errors import TicketError
from darrow_tickets_github.provider import origin_repository
from darrow_tickets_github.validation import check_attribution, norm_id


@settings(derandomize=True, max_examples=200)
@given(st.text(alphabet="0123456789", min_size=1, max_size=1000))
def test_id_normalization_never_wraps(digits: str) -> None:
    expected = digits.lstrip("0") or "0"
    assert norm_id(digits) == expected
    assert norm_id("#" + digits) == expected
    assert norm_id(norm_id(digits)) == expected


@settings(derandomize=True, max_examples=100)
@given(st.text())
def test_literal_option_value(value: str) -> None:
    assert parse("list", ["--search", value]).value("search") == value


@settings(derandomize=True, max_examples=100)
@given(
    st.text(alphabet="abcdefghijklmnopqrstuvwxyz0123456789-_", min_size=1, max_size=50)
)
def test_remote_transports_agree(name: str) -> None:
    expected = f"github.test/owner/{name}"
    for url in (
        f"https://{expected}.git",
        f"ssh://git@{expected}.git",
        f"git@github.test:owner/{name}.git",
    ):
        assert origin_repository(url) == expected


@pytest.mark.parametrize(
    "remote",
    [
        "local-path",
        "https://host",
        "https:///owner/name",
        "https://host/owner/name/extra",
        "git@host:owner/space name",
        "owner/name",
        "https://host//name",
    ],
)
def test_bad_remote(remote: str) -> None:
    with pytest.raises(TicketError):
        origin_repository(remote)


@pytest.mark.parametrize(
    "text",
    [
        "Generated by openapi-generator",
        "AI support is broken",
        "Create a Claude integration",
        "Co-authored-by: Human <h@test>",
    ],
)
def test_attribution_requires_tool_context(text: str) -> None:
    check_attribution(text)


@pytest.mark.parametrize(
    "text",
    [
        "Generated using Claude Code",
        "🤖",
        "Co-authored by Codex",
        "Co-authored-by: Person AI <x@y>",
        "Built with an AI",
    ],
)
def test_attribution_refusal(text: str) -> None:
    with pytest.raises(TicketError) as error:
        check_attribution(text)
    assert error.value.code == 6
